const INITIAL_PRODUCTS: BuildingProduct[] = [
  // 1. Structural Steel & Rebars
  {
    id: 'PRD-001',
    name: 'TMT 550D Rebar 12mm',
    category: 'Structural Steel',
    unit: 'Ton',
    unitCost: 56000,
    status: 'Active',
    currentStock: 45,
    minStock: 15,
    reorderLevel: 20,
    maxStock: 120,
    supplier: 'Tata Steel Ltd',
    purchaseDate: '2026-08-10',
    location: 'Tower-A Yard',
    skuPartNo: 'TATA-TMT-12',
    barcode: '890987654321',
    brand: 'Tata Tiscon',
    rack: 'Open Bay 1',
    bin: 'Stack A',
    description: 'Fe550D grade high-ductile steel for column and slab casting'
  },
  {
    id: 'PRD-002',
    name: 'TMT 550D Rebar 16mm',
    category: 'Structural Steel',
    unit: 'Ton',
    unitCost: 56500,
    status: 'Active',
    currentStock: 30,
    minStock: 10,
    reorderLevel: 15,
    maxStock: 100,
    supplier: 'JSW Steel',
    purchaseDate: '2026-08-12',
    location: 'Central Yard',
    skuPartNo: 'JSW-TMT-16',
    barcode: '890987654322',
    brand: 'JSW Neosteel',
    rack: 'Open Bay 2',
    bin: 'Stack B',
    description: '16mm heavy reinforcement bars for beam and column framing'
  },
  {
    id: 'PRD-003',
    name: 'GI Binding Wire (18 Gauge)',
    category: 'Structural Steel',
    unit: 'Kg',
    unitCost: 78,
    status: 'Active',
    currentStock: 350,
    minStock: 100,
    reorderLevel: 150,
    maxStock: 800,
    supplier: 'Local Hardware Traders',
    purchaseDate: '2026-08-15',
    location: 'Central Shed',
    skuPartNo: 'BW-GI-18G',
    barcode: '890456789012',
    brand: 'Standard GI',
    rack: 'R-01',
    bin: 'B-04',
    description: 'Galvanized annealed binding wire for tying rebar meshes'
  },

  // 2. Cement & Binding
  {
    id: 'PRD-004',
    name: 'OPC 53 Grade Cement',
    category: 'Cement & Binding',
    unit: 'Bags',
    unitCost: 385,
    status: 'Active',
    currentStock: 420,
    minStock: 100,
    reorderLevel: 150,
    maxStock: 1000,
    supplier: 'UltraTech Cement',
    purchaseDate: '2026-08-14',
    location: 'Central Shed',
    skuPartNo: 'ULT-OPC53',
    barcode: '890456123789',
    brand: 'UltraTech',
    rack: 'Shed 1',
    bin: 'Platform C',
    expiryDate: '2026-11-14',
    description: 'High-strength 53 Grade Ordinary Portland Cement for structural concrete'
  },
  {
    id: 'PRD-005',
    name: 'PPC Blended Cement',
    category: 'Cement & Binding',
    unit: 'Bags',
    unitCost: 360,
    status: 'Active',
    currentStock: 280,
    minStock: 80,
    reorderLevel: 120,
    maxStock: 800,
    supplier: 'ACC Limited',
    purchaseDate: '2026-08-11',
    location: 'Central Shed',
    skuPartNo: 'ACC-PPC-BAG',
    barcode: '890456123790',
    brand: 'ACC Suraksha',
    rack: 'Shed 1',
    bin: 'Platform D',
    expiryDate: '2026-11-11',
    description: 'Portland Pozzolana Cement for brickwork, blockwork, and plastering'
  },

  // 3. Aggregates & Sand
  {
    id: 'PRD-006',
    name: 'M-Sand (Manufactured Sand)',
    category: 'Aggregates & Sand',
    unit: 'Ton',
    unitCost: 1450,
    status: 'Active',
    currentStock: 85,
    minStock: 25,
    reorderLevel: 40,
    maxStock: 250,
    supplier: 'Deccan Crushers Ltd',
    purchaseDate: '2026-08-16',
    location: 'Central Yard',
    skuPartNo: 'AGG-MSAND-01',
    barcode: '890789123456',
    brand: 'Crushed Blue Metal',
    rack: 'Yard Stockpile',
    bin: 'Bay 1',
    description: 'Zone II washed manufactured sand for RCC structural mix'
  },
  {
    id: 'PRD-007',
    name: 'Coarse Aggregate (20mm Metal)',
    category: 'Aggregates & Sand',
    unit: 'Ton',
    unitCost: 1200,
    status: 'Active',
    currentStock: 110,
    minStock: 30,
    reorderLevel: 50,
    maxStock: 300,
    supplier: 'Deccan Crushers Ltd',
    purchaseDate: '2026-08-16',
    location: 'Central Yard',
    skuPartNo: 'AGG-20MM-GRANITE',
    barcode: '890789123457',
    brand: 'Crushed Granite',
    rack: 'Yard Stockpile',
    bin: 'Bay 2',
    description: 'Angular 20mm granite aggregate for slab, beam, and column concrete'
  },

  // 4. Brick & Masonry Blocks
  {
    id: 'PRD-008',
    name: 'AAC Lightweight Blocks (600x200x150mm)',
    category: 'Brick & Masonry Blocks',
    unit: 'Nos',
    unitCost: 65,
    status: 'Active',
    currentStock: 1800,
    minStock: 500,
    reorderLevel: 800,
    maxStock: 4000,
    supplier: 'Magicrete Building Solutions',
    purchaseDate: '2026-08-08',
    location: 'Tower-A Yard',
    skuPartNo: 'AAC-BLK-6IN',
    barcode: '890567123890',
    brand: 'Magicrete',
    rack: 'Open Yard 3',
    bin: 'Stack C',
    description: 'Autoclaved aerated concrete blocks for external and internal masonry walls'
  },
  {
    id: 'PRD-009',
    name: 'Standard Wire-Cut Red Bricks',
    category: 'Brick & Masonry Blocks',
    unit: 'Nos',
    unitCost: 11,
    status: 'Active',
    currentStock: 3500,
    minStock: 1000,
    reorderLevel: 1500,
    maxStock: 10000,
    supplier: 'Apex Kilns',
    purchaseDate: '2026-08-05',
    location: 'Central Yard',
    skuPartNo: 'BRK-CLAY-STD',
    barcode: '890567123891',
    brand: 'Apex',
    rack: 'Open Yard 4',
    bin: 'Stack D',
    description: 'First-class kiln-burnt clay bricks for perimeter walls and foundations'
  },

  // 5. Formwork & Shuttering
  {
    id: 'PRD-010',
    name: 'Film-Faced Shuttering Plywood (12mm BWP)',
    category: 'Hardware & Fasteners',
    unit: 'Nos',
    unitCost: 1850,
    status: 'Active',
    currentStock: 120,
    minStock: 30,
    reorderLevel: 50,
    maxStock: 300,
    supplier: 'CenturyPly Infrastructure',
    purchaseDate: '2026-08-09',
    location: 'Central Shed',
    skuPartNo: 'SHT-PLY-12MM',
    barcode: '890678234901',
    brand: 'Century Marine',
    rack: 'R-03',
    bin: 'B-01',
    description: 'Phenolic film-faced shuttering sheets (8x4 ft) for slab and beam centering'
  },
  {
    id: 'PRD-011',
    name: 'Adjustable Telescopic Steel Props (Jack Props)',
    category: 'Hardware & Fasteners',
    unit: 'Nos',
    unitCost: 1250,
    status: 'Active',
    currentStock: 250,
    minStock: 50,
    reorderLevel: 80,
    maxStock: 500,
    supplier: 'BuildPro Scaffolds',
    purchaseDate: '2026-08-02',
    location: 'Basement Staging',
    skuPartNo: 'SCF-PROP-2M',
    barcode: '890678234902',
    brand: 'BuildPro',
    rack: 'Bay S-1',
    bin: 'Rack P',
    description: '2m to 3.5m adjustable heavy-duty MS props for slab formwork support'
  },

  // 6. Plumbing & Electrical
  {
    id: 'PRD-012',
    name: 'CPVC Pipe SDR 11 - 1" (3 Meter Length)',
    category: 'Plumbing & Electrical',
    unit: 'Nos',
    unitCost: 420,
    status: 'Active',
    currentStock: 160,
    minStock: 40,
    reorderLevel: 60,
    maxStock: 300,
    supplier: 'Astral Pipes Ltd',
    purchaseDate: '2026-08-13',
    location: 'Central Shed',
    skuPartNo: 'AST-CPVC-1IN',
    barcode: '890123987456',
    brand: 'Astral',
    rack: 'R-04',
    bin: 'Pipe Rack A',
    description: 'Chlorinated polyvinyl chloride pressure pipes for concealed water supply'
  },
  {
    id: 'PRD-013',
    name: 'PVC Heavy Electrical Conduit 25mm (3m)',
    category: 'Plumbing & Electrical',
    unit: 'Nos',
    unitCost: 85,
    status: 'Active',
    currentStock: 320,
    minStock: 100,
    reorderLevel: 150,
    maxStock: 600,
    supplier: 'Finolex Industries',
    purchaseDate: '2026-08-12',
    location: 'Central Shed',
    skuPartNo: 'FIN-CND-25MM',
    barcode: '890123987457',
    brand: 'Finolex',
    rack: 'R-04',
    bin: 'Pipe Rack B',
    description: 'High-impact rigid PVC electrical conduit for slab and wall slab embedding'
  },

  // 7. Lubricants & Oils (Plant Equipment)
  {
    id: 'PRD-014',
    name: 'Castrol Optigear 320',
    category: 'Lubricants & Oils',
    unit: 'Litre',
    unitCost: 450,
    status: 'Active',
    currentStock: 10,
    minStock: 5,
    reorderLevel: 10,
    maxStock: 100,
    supplier: 'Castrol India Ltd',
    purchaseDate: '2026-08-17',
    location: 'Central Yard',
    skuPartNo: 'CST-OG320',
    barcode: '890123456789',
    brand: 'Castrol',
    rack: 'R-02',
    bin: 'B-14',
    description: 'Heavy gear industrial oil for batching plants, transit mixers, and cranes'
  }
];
